version: "3"

services:
   home-rss:
      container_name: home-rss
      build: ./
      image: home-rss/latest
      restart: unless-stopped
      ports:
         - 7474:8080
      environment:
         - NODE_ENV=development
      volumes: # For Hot Reload
         - ./:/home-rss
         - /home-rss/node_modules
      command: npm run dev
