version: "3"

services:
  home-rss:
    container_name: home-rss
    build: ./
    image: home-rss/latest
    restart: unless-stopped
    ports:
      - 7474:8080
    environment:
      - IPTV_SOURCE=$IPTV_SOURCE
